version: "3.8"

services:

  app:
    build: .
    command: >
      uvicorn product_price_app.main:app --host=0.0.0.0 --port=8080 --reload
    volumes:
      - .:/app
    ports:
      - 8080:8080

  external_api:
    image: python:3.12-slim
    command: python3 -m http.server -d /app/external_api 8081
    volumes:
      - ./external_api:/app/external_api
    ports:
      - 8081:8081
